import { useEffect, useState } from 'react'
import PageHeader from '../../components/common/PageHeader'
import DataTable from '../../components/common/DataTable'
import Badge from '../../components/common/Badge'
import SkeletonLoader from '../../components/common/SkeletonLoader'
import * as adminService from '../../services/adminService'
import { formatDate } from '../../utils/formatters'

export default function AdminReports() {
  const [reports, setReports] = useState(null)
  useEffect(() => { adminService.getAdminInterviewReports().then(setReports) }, [])
  if (!reports) return <SkeletonLoader rows={4} />
  const columns = [
    { key: 'id', header: 'Report' },
    { key: 'sessionId', header: 'Session', render: (item) => `#${item.sessionId}` },
    { key: 'overallScore', header: 'Score', render: (item) => <Badge tone={item.overallScore >= 70 ? 'success' : 'warning'}>{item.overallScore}</Badge> },
    { key: 'createdAt', header: 'Created', render: (item) => formatDate(item.createdAt) },
  ]
  return (
    <div>
      <PageHeader title="Platform Reports" subtitle="Live interview reports generated by the platform." />
      <DataTable columns={columns} data={reports} />
    </div>
  )
}
