import Badge from '../../components/common/Badge'

const SECTIONS = [
  ['Acceptance of terms', 'By creating an account and using Interview IQ, you agree to these terms and conditions.'],
  ['Use of the platform', 'Interview IQ is provided for personal career-preparation use. You agree not to misuse the platform, including uploading harmful content or attempting to disrupt the service.'],
  ['Subscriptions', 'Paid plans renew automatically until cancelled. Cancelling stops future renewals; access continues until the end of the current billing period.'],
  ['AI-generated content', 'Scores, feedback, and recommendations are generated by AI systems and provided as guidance only, without guarantee of accuracy or interview outcomes.'],
  ['Account termination', 'We may suspend accounts that violate these terms. You may delete your account at any time from Settings.'],
  ['Changes to these terms', 'We may update these terms from time to time; continued use after changes constitutes acceptance.'],
]

export default function Terms() {
  return (
    <div className="max-w-3xl mx-auto px-4 md:px-8 py-16">
      <Badge tone="blue">Legal</Badge>
      <h1 className="font-display font-bold text-3xl md:text-4xl text-text-primary mt-4">Terms and Conditions</h1>
      <p className="text-sm text-text-muted mt-2">Last updated: July 19, 2026 — placeholder terms for a student project, not legal advice.</p>
      <div className="mt-10 space-y-8">
        {SECTIONS.map(([title, body]) => (
          <div key={title}>
            <h2 className="font-display font-semibold text-text-primary text-lg mb-2">{title}</h2>
            <p className="text-sm text-text-secondary leading-relaxed">{body}</p>
          </div>
        ))}
      </div>
    </div>
  )
}
